name: Supabase Project Ping

on:
  schedule:
    # 3일에 한 번씩 자정(UTC 기준)에 실행
    - cron: '0 0 */3 * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase RPC
        # 테이블 대신 RPC 함수를 호출하여 프로젝트 활성 상태를 유지합니다.
        run: |
          curl -i -X POST \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            "https://gyehophknpfwheywfcpk.supabase.co/rest/v1/rpc/hello_world"
